using System.Collections.Generic;

public static class BlendShapeMapper
{
    public static readonly Dictionary<string, string> arkitToVSeeFaceMap = new Dictionary<string, string>()
    {
        {"BrowDownLeft", "/vface/browDownLeft"},
        {"BrowDownRight", "/vface/browDownRight"},
        {"BrowInnerUp", "/vface/browInnerUp"},
        {"CheekPuff", "/vface/cheekPuff"},
        {"CheekSquintLeft", "/vface/cheekSquintLeft"},
        {"CheekSquintRight", "/vface/cheekSquintRight"},
        {"EyeBlinkLeft", "/vface/eyeBlinkLeft"},
        {"EyeBlinkRight", "/vface/eyeBlinkRight"},
        {"EyeLookDownLeft", "/vface/eyeLookDownLeft"},
        {"EyeLookDownRight", "/vface/eyeLookDownRight"},
        {"EyeLookInLeft", "/vface/eyeLookInLeft"},
        {"EyeLookInRight", "/vface/eyeLookInRight"},
        {"EyeLookOutLeft", "/vface/eyeLookOutLeft"},
        {"EyeLookOutRight", "/vface/eyeLookOutRight"},
        {"EyeLookUpLeft", "/vface/eyeLookUpLeft"},
        {"EyeLookUpRight", "/vface/eyeLookUpRight"},
        {"EyeSquintLeft", "/vface/eyeSquintLeft"},
        {"EyeSquintRight", "/vface/eyeSquintRight"},
        {"EyeWideLeft", "/vface/eyeWideLeft"},
        {"EyeWideRight", "/vface/eyeWideRight"},
        {"JawForward", "/vface/jawForward"},
        {"JawLeft", "/vface/jawLeft"},
        {"JawOpen", "/vface/jawOpen"},
        {"JawRight", "/vface/jawRight"},
        {"MouthClose", "/vface/mouthClose"},
        {"MouthDimpleLeft", "/vface/mouthDimpleLeft"},
        {"MouthDimpleRight", "/vface/mouthDimpleRight"},
        {"MouthFrownLeft", "/vface/mouthFrownLeft"},
        {"MouthFrownRight", "/vface/mouthFrownRight"},
        {"MouthFunnel", "/vface/mouthFunnel"},
        {"MouthLeft", "/vface/mouthLeft"},
        {"MouthLowerDownLeft", "/vface/mouthLowerDownLeft"},
        {"MouthLowerDownRight", "/vface/mouthLowerDownRight"},
        {"MouthPressLeft", "/vface/mouthPressLeft"},
        {"MouthPressRight", "/vface/mouthPressRight"},
        {"MouthPucker", "/vface/mouthPucker"},
        {"MouthRight", "/vface/mouthRight"},
        {"MouthRollLower", "/vface/mouthRollLower"},
        {"MouthRollUpper", "/vface/mouthRollUpper"},
        {"MouthShrugLower", "/vface/mouthShrugLower"},
        {"MouthShrugUpper", "/vface/mouthShrugUpper"},
        {"MouthSmileLeft", "/vface/mouthSmileLeft"},
        {"MouthSmileRight", "/vface/mouthSmileRight"},
        {"MouthStretchLeft", "/vface/mouthStretchLeft"},
        {"MouthStretchRight", "/vface/mouthStretchRight"},
        {"MouthUpperUpLeft", "/vface/mouthUpperUpLeft"},
        {"MouthUpperUpRight", "/vface/mouthUpperUpRight"},
        {"NoseSneerLeft", "/vface/noseSneerLeft"},
        {"NoseSneerRight", "/vface/noseSneerRight"},
    };

    public static readonly Dictionary<string, string> BlendShapeMap = new()
    {
        { "BrowDownLeft", "Sorrow" },
        { "BrowDownRight", "Sorrow" },
        { "BrowInnerUp", "Neutral" },
        { "BrowOuterUpLeft", "Joy" },
        { "BrowOuterUpRight", "Joy" },
        { "CheekPuff", "Fun" },
        { "CheekSquintLeft", "Fun" },
        { "CheekSquintRight", "Fun" },
        { "EyeBlinkLeft", "Blink_L" },
        { "EyeBlinkRight", "Blink_R" },
        { "EyeLookDownLeft", "LookDown" },
        { "EyeLookDownRight", "LookDown" },
        { "EyeLookUpLeft", "LookUp" },
        { "EyeLookUpRight", "LookUp" },
        { "EyeLookInLeft", "LookLeft" },
        { "EyeLookOutRight", "LookLeft" },
        { "EyeLookInRight", "LookRight" },
        { "EyeLookOutLeft", "LookRight" },
        { "EyeSquintLeft", "Sorrow" },
        { "EyeSquintRight", "Sorrow" },
        { "EyeWideLeft", "Surprise" }, // 없으면 무시
        { "EyeWideRight", "Surprise" }, // 없으면 무시
        { "JawForward", "Neutral" },
        { "JawLeft", "Neutral" },
        { "JawRight", "Neutral" },
        { "JawOpen", "A" },
        { "MouthClose", "I" },
        { "MouthFunnel", "U" },
        { "MouthPucker", "O" },
        { "MouthLeft", "Neutral" },
        { "MouthRight", "Neutral" },
        { "MouthSmileLeft", "Joy" },
        { "MouthSmileRight", "Joy" },
        { "MouthFrownLeft", "Angry" },
        { "MouthFrownRight", "Angry" },
        { "MouthDimpleLeft", "Neutral" },
        { "MouthDimpleRight", "Neutral" },
        { "MouthStretchLeft", "Angry" },
        { "MouthStretchRight", "Angry" },
        { "MouthRollLower", "Neutral" },
        { "MouthRollUpper", "Neutral" },
        { "MouthShrugLower", "Sorrow" },
        { "MouthShrugUpper", "Sorrow" },
        { "MouthPressLeft", "Neutral" },
        { "MouthPressRight", "Neutral" },
        { "MouthLowerDownLeft", "Sorrow" },
        { "MouthLowerDownRight", "Sorrow" },
        { "MouthUpperUpLeft", "E" },
        { "MouthUpperUpRight", "E" },
        { "NoseSneerLeft", "Fun" },
        { "NoseSneerRight", "Fun" },
        { "TongueOut", "Neutral" }
    };

    public static readonly Dictionary<string, string> ARKitToFacialMocap = new()
    {
        { "BrowInnerUp", "browInnerUp" },
        { "BrowOuterUpLeft", "browOuterUp_L" },
        { "BrowOuterUpRight", "browOuterUp_R" },
        { "CheekPuff", "cheekPuff" },
        { "CheekSquintLeft", "cheekSquint_L" },
        { "CheekSquintRight", "cheekSquint_R" },
        { "EyeBlinkLeft", "eyeBlink_L" },
        { "EyeBlinkRight", "eyeBlink_R" },
        { "EyeLookDownLeft", "eyeLookDown_L" },
        { "EyeLookDownRight", "eyeLookDown_R" },
        { "EyeLookInLeft", "eyeLookIn_L" },
        { "EyeLookInRight", "eyeLookIn_R" },
        { "EyeLookOutLeft", "eyeLookOut_L" },
        { "EyeLookOutRight", "eyeLookOut_R" },
        { "EyeLookUpLeft", "eyeLookUp_L" },
        { "EyeLookUpRight", "eyeLookUp_R" },
        { "EyeSquintLeft", "eyeSquint_L" },
        { "EyeSquintRight", "eyeSquint_R" },
        { "EyeWideLeft", "eyeWide_L" },
        { "EyeWideRight", "eyeWide_R" },
        { "JawForward", "jawForward" },
        { "JawLeft", "jawLeft" },
        { "JawOpen", "jawOpen" },
        { "JawRight", "jawRight" },
        { "MouthClose", "mouthClose" },
        { "MouthDimpleLeft", "mouthDimple_L" },
        { "MouthDimpleRight", "mouthDimple_R" },
        { "MouthFrownLeft", "mouthFrown_L" },
        { "MouthFrownRight", "mouthFrown_R" },
        { "MouthFunnel", "mouthFunnel" },
        { "MouthLeft", "mouthLeft" },
        { "MouthLowerDownLeft", "mouthLowerDown_L" },
        { "MouthLowerDownRight", "mouthLowerDown_R" },
        { "MouthPressLeft", "mouthPress_L" },
        { "MouthPressRight", "mouthPress_R" },
        { "MouthPucker", "mouthPucker" },
        { "MouthRollLower", "mouthRollLower" },
        { "MouthRollUpper", "mouthRollUpper" },
        { "MouthRight", "mouthRight" },
        { "MouthShrugLower", "mouthShrugLower" },
        { "MouthShrugUpper", "mouthShrugUpper" },
        { "MouthSmileLeft", "mouthSmile_L" },
        { "MouthSmileRight", "mouthSmile_R" },
        { "MouthStretchLeft", "mouthStretch_L" },
        { "MouthStretchRight", "mouthStretch_R" },
        { "MouthUpperUpLeft", "mouthUpperUp_L" },
        { "MouthUpperUpRight", "mouthUpperUp_R" },
        { "NoseSneerLeft", "noseSneer_L" },
        { "NoseSneerRight", "noseSneer_R" },
        { "TongueOut", "tongueOut" }
        // 필요하면 추가
    };
}